# -*- coding: utf-8 -*-
"""area_of_triangle

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SeoZ71ENUNX2OdZZJOOeNvK4TQhPzR0l
"""

a=2
b=4
x=0.5*(a*b)
print("Area of Triangle is: ",x)