# -*- coding: utf-8 -*-
"""area_of_rectangle

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SeoZ71ENUNX2OdZZJOOeNvK4TQhPzR0l
"""

l=2
b=4
x=(a*b)
print("Area of Rectangle is: ",x)