# -*- coding: utf-8 -*-
"""radius_of_circle

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SeoZ71ENUNX2OdZZJOOeNvK4TQhPzR0l
"""

r=2
pi=3.14
x=pi*(r*r)
print("Area of circle is: ",x)