# -*- coding: utf-8 -*-
"""celcius_to_farenheit

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SeoZ71ENUNX2OdZZJOOeNvK4TQhPzR0l
"""

c=38
f=(c*1.8)+32
print("Celcius to Farenheit is: ",f)