# -*- coding: utf-8 -*-
"""circumference_of_circle

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SeoZ71ENUNX2OdZZJOOeNvK4TQhPzR0l
"""

r=6
p=3.142
c=2*p*r
print("perimeter of square is: ",c)