# -*- coding: utf-8 -*-
"""perimeter_of_square

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SeoZ71ENUNX2OdZZJOOeNvK4TQhPzR0l
"""

a=6
p=4*a
print("perimeter of square is: ",p)