# -*- coding: utf-8 -*-
"""swapping_of_numbers

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SeoZ71ENUNX2OdZZJOOeNvK4TQhPzR0l
"""

a=12
b=78
print("Before swapping",a,b)
h=a
a=b
b=h
print("After swapping",a,b)